Name=input("Enter Name :")
Email=input("Enter email adress :")
Phno=input("Enter Phone NUmber :")
print(f"Your name is ::{Name}")
print(f"Ypur Email address is ::{Email}")
print(f"Your Phone NUmber is {Phno}")
